ignore:
  - "test/"
  - "vendor/"
  - "platform/ios/test"
  - "platform/darwin/test"
flags:
  ios:
    paths:
      - "platform/ios/"  - "platform/darwin/test"
coverage:
  status:
    project:
      default:
        threshold: 1%
